name: diary
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background_geolocation: ^1.7.0
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.25
  flutter_statusbarcolor: ^0.2.3
  flutter_circular_chart: ^0.1.0
  flutter_state_notifier: ^0.3.0
  flutter_map: ^0.8.2
  rflutter_alert: ^1.0.3
  path_provider: ^1.6.5
  share_extend: ^1.1.1
  device_preview: ^0.3.0+1
  sized_context: ^0.2.1
  unicorndial: ^1.1.5
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  csv: ^4.0.3
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/annotation_pin.png
    - assets/my_position_pin.png
    - assets/wom_pin.png
    - assets/black_circle_pin.png
    - assets/diary_logo.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 700
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600