name: diary
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background_geolocation: ^1.7.3
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.26+2
  flutter_statusbarcolor: ^0.2.3
  flutter_circular_chart: ^0.1.0
  flutter_state_notifier: ^0.3.0
  rflutter_alert: ^1.0.3
  path_provider: ^1.6.7
#  share_extend: ^1.1.1
  esys_flutter_share: ^1.0.2
  device_preview: ^0.4.4
  sized_context: ^0.2.1+1
  unicorndial:
    git: git://github.com/giandifra/unicornspeeddial.git
  firebase_analytics: ^5.0.11
  permission_handler: ^4.4.0+hotfix.4
  firebase_crashlytics: ^0.1.3+3
  csv: ^4.0.3
  uuid: ^2.0.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_colorpicker: ^0.3.4
  package_info: ^0.4.0+17
  file_picker: ^1.6.3+2
  sliding_sheet: ^0.3.3
  freezed_annotation: ^0.7.1
  meta: ^1.1.8
  dartz:
  intl:
  dart_geohash: ^1.0.2
  url_launcher: ^5.4.5
  equatable:
  moor: # use the latest version
  moor_flutter: # use the latest version
  path:


dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  moor_generator: # use the latest version
  freezed:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/annotation_pin.png
    - assets/my_position_pin.png
    - assets/wom_pin.png
    - assets/black_circle_pin.png
    - assets/diary_logo.png
    - assets/selected_pin.png
    - assets/wom_pocket_logo.png
    - assets/annotated_pin.png
    - assets/normal_map_style.json
    - assets/dark_map_style.json

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 700
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf